# Generated by Django 3.1.7 on 2021-03-19 10:04

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='N/A', max_length=200)),
                ('last_name', models.CharField(blank=True, default='N/A', max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Other', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='N/A', max_length=400)),
                ('birth_date', models.DateField(blank=True, default='N/A', null=True)),
                ('phone', models.CharField(blank=True, default='N/A', max_length=200)),
                ('email', models.CharField(blank=True, default='N/A', max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=50, null=True)),
                ('blood_type', models.CharField(choices=[('APOS', 'A+'), ('ANEG', 'A-'), ('BPOS', 'B+'), ('BNEG', 'B-'), ('OPOS', 'O+'), ('ONEG', 'O-'), ('ABPOS', 'AB+'), ('ABNEG', 'AB-'), ('UNKNOWN', 'Unknown')], default='Unknown', max_length=100, null=True)),
                ('contact_name', models.CharField(blank=True, default='N/A', max_length=200)),
                ('contact_relationship', models.CharField(blank=True, default='N/A', max_length=200)),
                ('contact_phone', models.CharField(blank=True, default='N/A', max_length=200)),
                ('contact_email', models.CharField(blank=True, default='N/A', max_length=200)),
                ('insurance_policy_provider', models.CharField(blank=True, default='N/A', max_length=200)),
                ('insurance_policy_number', models.CharField(blank=True, default='N/A', max_length=200)),
                ('bed_location', models.CharField(blank=True, default='N/A', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vital', models.CharField(choices=[('SYS_BP', 'Systolic Blood Pressure'), ('DIA_BP', 'Diastolic Blood Pressure'), ('HR', 'Heart Rate'), ('BT', 'Body Temperature'), ('RR', 'Respiratory Rate')], max_length=100, null=True)),
                ('value', models.DecimalField(decimal_places=2, default='0.00', max_digits=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_nurse', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_patient', to='hms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_nurse', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_patient', to='hms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out')], max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitalization_nurse', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitalization_patient', to='hms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.CharField(blank=True, max_length=200)),
                ('reaction', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('SFX', 'Side Effect'), ('ALGY', 'Allergy')], max_length=100, null=True)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergy_nurse', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergy_patient', to='hms.patient')),
            ],
        ),
    ]
